version: "2"

services:
  database:
    container_name: de_database
    image: mysql:8
    volumes:
      - ./db-entrypoint/:/docker-entrypoint-initdb.d/
      - ./sql/:/scripts/
      - ./dataset:/dataset
    environment:
      MYSQL_PORT: 3306
      MYSQL_USER: local
      MYSQL_PASSWORD: local123
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: companydb
    ports:
      - 3306:3306
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 20
    command: --secure-file-priv=""